# Generated by Django 3.0.2 on 2020-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='slug',
            field=models.SlugField(blank=True, help_text='This slug is used when building ticket IDs.Once set, try not to change it or e-mailing may get messy.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
