# Generated by Django 3.0.2 on 2020-02-04 16:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0002_auto_20200204_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('problems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('submitter_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact name')),
                ('submitter_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company')),
                ('submitter_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number')),
                ('submitter_email', models.EmailField(blank=True, help_text='The submitter will receive an email for all public follow-ups left for this task.', max_length=254, null=True, verbose_name='Submitter E-Mail')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate')], default=1, verbose_name='Status')),
                ('priority', models.IntegerField(blank=3, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Normal'), (4, '4. Low'), (5, '5. Very Low')], default=3, help_text='1 = Highest Priority, 5 = Low Priority', verbose_name='Priority')),
                ('is_customer', models.BooleanField(default=False, verbose_name='É cliente')),
                ('customer_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código do cliente')),
                ('need_paper', models.BooleanField(default=False, verbose_name='Tem papel')),
                ('resolution_report', models.TextField(blank=True, help_text='The resolution provided to the customer by our staff.', null=True, verbose_name='Relatório final')),
                ('secret_key', models.CharField(default=helpdesk.models.make_secret, max_length=36, verbose_name='Secret key needed for viewing/editing ticket by non-logged in users')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Queue', verbose_name='Queue')),
                ('tecnico_de_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_de_campo', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de campo')),
                ('tecnico_pre_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_pre_diagnostico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico pré diagnóstico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
