# Generated by Django 3.0.2 on 2020-02-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('question', models.CharField(help_text='Pergunta para formulário de abertura de tickets', max_length=256, verbose_name='Question')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Queue', verbose_name='Queue')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('queue', 'order'),
            },
        ),
    ]
