# Generated by Django 3.0.3 on 2020-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='losses',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=16, verbose_name='Prejuízo'),
        ),
    ]
